// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load deterministically: .env.local first, then .env. dotenv never
// overwrites a key that's already set, so .env.local wins on any divergence
// (what we want on a dev machine).
dotenv.config({ path: path.resolve(__dirname, ".env.local") });
dotenv.config({ path: path.resolve(__dirname, ".env") });

const PROD_HOST = "ep-restless-silence";
const DEV_HOST = "ep-bold-frost";

function resolveDatasourceUrl(): string {
  const target = process.env["PRISMA_TARGET"];

  if (target !== "dev" && target !== "prod") {
    throw new Error(
      "PRISMA_TARGET must be 'dev' or 'prod' — refusing to resolve a database.",
    );
  }

  if (target === "dev") {
    const url = process.env["SEED_DATABASE_URL"];
    if (!url) {
      throw new Error(
        "PRISMA_TARGET=dev but SEED_DATABASE_URL is not set — refusing to fall back to DATABASE_URL.",
      );
    }
    if (url.includes(PROD_HOST)) {
      throw new Error("PRISMA_TARGET=dev but resolved a PROD host — aborting.");
    }
    return url;
  }

  const url = process.env["DATABASE_URL"];
  if (!url) {
    throw new Error("PRISMA_TARGET=prod but DATABASE_URL is not set.");
  }
  if (url.includes(DEV_HOST)) {
    throw new Error("PRISMA_TARGET=prod but resolved a DEV host — aborting.");
  }
  return url;
}

const resolvedUrl = resolveDatasourceUrl();

// schema.prisma declares `url = env("DATABASE_URL")` (not editable per task
// constraints), and the Prisma CLI resolves that literal env() at schema-load
// time regardless of `datasource.url` below — so `datasource.url` alone does
// NOT redirect `migrate`/`db` commands away from whatever DATABASE_URL is set
// to. Overwriting process.env.DATABASE_URL here (in-process only, no file
// write) is what actually makes PRISMA_TARGET=dev connect to
// SEED_DATABASE_URL instead of prod.
process.env["DATABASE_URL"] = resolvedUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolvedUrl,
  },
});
