export const PLATFORM_NAME = 'REIblast'
export const TAGLINE = 'From list to blast — close more deals, faster'
export const CORE_PRICE = 57
export const PROMO_CODE = 'ARISTUDENT'
export const JV_SPLIT_CORE = '50/50'
export const MAO_MULTIPLIER = 0.70
export const GHL_APP_URL = 'https://app.reiblast.app'
export const TOOLS_URL = 'https://tools.reiblast.app'
export const MARKETING_URL = 'https://reiblast.app'
