// PLACEHOLDER SEED DATA — every price, credit cost, allowance, tagline, hook, and
// compare-copy string below is a dummy value for foundation/dev work. None of this
// is approved pricing or copy. Do not ship copy or numbers from this file as-is.
//
// Read via lib/catalog.ts — do not import this file directly from components.

import type { Bundle, Catalog, OpDirectService, Pack, SoloPlan, Tool } from "@/types/catalog";

const tools: Tool[] = [
  {
    type: "tool",
    slug: "rei-score",
    name: "REIscore",
    tagline: "Placeholder tagline: instant deal scoring.",
    hook: "Placeholder hook: know if it's a deal in seconds.",
    icon: "/brand/icons/rei-score.svg",
    wordmark: "/brand/wordmarks/rei-score.png",
    category: "Analysis",
    unit: "run",
    href: "/rei-score",
    compareCopy: ["Placeholder: ARV + comps", "Placeholder: offer ranges", "Placeholder: MAO calc"],
  },
  {
    type: "tool",
    slug: "rei-pack",
    name: "REIpack",
    tagline: "Placeholder tagline: buyer list packaging.",
    hook: "Placeholder hook: package deals for your buyer list fast.",
    icon: "/brand/icons/rei-pack.svg",
    wordmark: "/brand/wordmarks/rei-pack.png",
    category: "Dispo",
    unit: "run",
    href: "/rei-pack",
    compareCopy: ["Placeholder: flyer generation", "Placeholder: buyer matching"],
  },
  {
    type: "tool",
    slug: "rei-ask",
    name: "REIask",
    tagline: "Placeholder tagline: AI deal Q&A.",
    hook: "Placeholder hook: ask anything about your pipeline.",
    icon: "/brand/icons/rei-ask.svg",
    wordmark: "/brand/wordmarks/rei-ask.png",
    category: "AI",
    unit: "send",
    href: "/rei-ask",
    compareCopy: ["Placeholder: natural-language queries", "Placeholder: deal summaries"],
  },
  {
    type: "tool",
    slug: "rei-scrub",
    name: "REIscrub",
    tagline: "Placeholder tagline: clean lead lists.",
    hook: "Placeholder hook: dedupe and scrub before you dial.",
    icon: "/brand/icons/rei-scrub.svg",
    wordmark: "/brand/wordmarks/rei-scrub.png",
    category: "Leads",
    unit: "lookup",
    href: "/rei-scrub",
    compareCopy: ["Placeholder: DNC scrub", "Placeholder: dedupe"],
  },
  {
    type: "tool",
    slug: "rei-dispo",
    name: "REIdispo",
    tagline: "Placeholder tagline: dispo automation.",
    hook: "Placeholder hook: move contracts faster.",
    icon: "/brand/icons/rei-dispo.svg",
    wordmark: "/brand/wordmarks/rei-dispo.png",
    category: "Dispo",
    unit: "run",
    href: "/rei-dispo",
    compareCopy: ["Placeholder: buyer blasts", "Placeholder: contract tracking"],
  },
  {
    type: "tool",
    slug: "rei-acq",
    name: "REIacq",
    tagline: "Placeholder tagline: acquisitions pipeline.",
    hook: "Placeholder hook: manage acquisitions end-to-end.",
    icon: "/brand/icons/rei-acq.svg",
    wordmark: "/brand/wordmarks/rei-acq.png",
    category: "Acquisitions",
    unit: "run",
    href: "/rei-acq",
    compareCopy: ["Placeholder: pipeline stages", "Placeholder: offer tracking"],
  },
  {
    type: "tool",
    slug: "rei-close",
    name: "REIclose",
    tagline: "Placeholder tagline: closing coordination.",
    hook: "Placeholder hook: get to close without the chaos.",
    icon: "/brand/icons/rei-close.svg",
    wordmark: "/brand/wordmarks/rei-close.png",
    category: "Closing",
    unit: "run",
    href: "/rei-close",
    compareCopy: ["Placeholder: title coordination", "Placeholder: doc tracking"],
  },
  {
    type: "tool",
    slug: "rei-site",
    name: "REIsite",
    tagline: "Placeholder tagline: landing pages for deals.",
    hook: "Placeholder hook: spin up a deal site in minutes.",
    icon: "/brand/icons/rei-site.svg",
    wordmark: "/brand/wordmarks/rei-site.png",
    category: "Marketing",
    unit: "run",
    href: "/rei-site",
    free: true,
    compareCopy: ["Placeholder: hosted pages", "Placeholder: lead capture form"],
  },
  {
    type: "tool",
    slug: "rei-kit",
    name: "REIkit",
    tagline: "Placeholder tagline: contract + doc templates.",
    hook: "Placeholder hook: every template you need, ready to send.",
    icon: "/brand/icons/rei-kit.svg",
    wordmark: "/brand/wordmarks/rei-kit.png",
    category: "Docs",
    unit: "run",
    href: "/rei-kit",
    comingSoon: true,
    compareCopy: ["Placeholder: state-specific contracts", "Placeholder: e-sign ready"],
  },
];

const packs: Pack[] = [
  { type: "pack", id: "pack-rei-score-10", toolSlug: "rei-score", name: "10 runs", units: 10, price: 19 },
  { type: "pack", id: "pack-rei-score-50", toolSlug: "rei-score", name: "50 runs", units: 50, price: 79 },
  { type: "pack", id: "pack-rei-pack-10", toolSlug: "rei-pack", name: "10 runs", units: 10, price: 15 },
  { type: "pack", id: "pack-rei-ask-100", toolSlug: "rei-ask", name: "100 sends", units: 100, price: 25 },
  { type: "pack", id: "pack-rei-scrub-1000", toolSlug: "rei-scrub", name: "1,000 lookups", units: 1000, price: 29 },
  { type: "pack", id: "pack-rei-dispo-10", toolSlug: "rei-dispo", name: "10 runs", units: 10, price: 19 },
  { type: "pack", id: "pack-rei-acq-10", toolSlug: "rei-acq", name: "10 runs", units: 10, price: 19 },
  { type: "pack", id: "pack-rei-close-10", toolSlug: "rei-close", name: "10 runs", units: 10, price: 15 },
];

// Core is the baseline bundle at price 0 (+$0). Plus/Pro carry OP-only additive
// prices on top of the 57 core membership — no bundle price includes the 57.
const bundles: Bundle[] = [
  {
    type: "bundle",
    id: "bundle-core",
    slug: "core",
    name: "Core",
    tagline: "Placeholder tagline: what's included in every membership.",
    price: 0,
    covers: ["rei-score", "rei-scrub", "rei-site"],
    allowances: { "rei-score": 10, "rei-scrub": 500 },
    compareCopy: ["Placeholder: included with membership", "Placeholder: baseline analysis + scrub"],
  },
  {
    type: "bundle",
    id: "bundle-plus",
    slug: "plus",
    name: "Plus",
    tagline: "Placeholder tagline: for active dispo.",
    price: 47,
    covers: ["rei-score", "rei-scrub", "rei-site", "rei-pack", "rei-dispo", "rei-ask"],
    allowances: { "rei-score": 50, "rei-scrub": 2000, "rei-pack": 25, "rei-dispo": 25, "rei-ask": 300 },
    compareCopy: ["Placeholder: everything in Core", "Placeholder: dispo + AI included"],
  },
  {
    type: "bundle",
    id: "bundle-pro",
    slug: "pro",
    name: "Pro",
    tagline: "Placeholder tagline: full pipeline coverage.",
    price: 97,
    covers: [
      "rei-score",
      "rei-scrub",
      "rei-site",
      "rei-pack",
      "rei-dispo",
      "rei-ask",
      "rei-acq",
      "rei-close",
    ],
    allowances: {
      "rei-score": 200,
      "rei-scrub": 10000,
      "rei-pack": 100,
      "rei-dispo": 100,
      "rei-ask": 1000,
      "rei-acq": 100,
      "rei-close": 50,
    },
    compareCopy: ["Placeholder: everything in Plus", "Placeholder: acquisitions + closing included"],
  },
];

const soloPlans: SoloPlan[] = [
  { type: "solo-plan", id: "solo-rei-score", toolSlug: "rei-score", name: "REIscore solo", price: 29, allowance: 25 },
  { type: "solo-plan", id: "solo-rei-ask", toolSlug: "rei-ask", name: "REIask solo", price: 19, allowance: 200 },
  { type: "solo-plan", id: "solo-rei-acq", toolSlug: "rei-acq", name: "REIacq solo", price: 39, allowance: 25 },
];

const opDirectServices: OpDirectService[] = [
  {
    type: "op-direct",
    id: "op-direct-cold-calling",
    slug: "cold-calling",
    name: "OP Cold Calling",
    tagline: "Placeholder tagline: done-for-you dialing.",
    hook: "Placeholder hook: our team calls your list for you.",
    price: 500,
    compareCopy: ["Placeholder: dedicated caller", "Placeholder: weekly reporting"],
  },
  {
    type: "op-direct",
    id: "op-direct-va-support",
    slug: "va-support",
    name: "OP VA Support",
    tagline: "Placeholder tagline: dedicated virtual assistant.",
    hook: "Placeholder hook: hand off the busywork.",
    price: 800,
    compareCopy: ["Placeholder: 20hrs/week", "Placeholder: trained on your SOPs"],
  },
];

export const catalog: Catalog = {
  tools,
  packs,
  bundles,
  soloPlans,
  opDirectServices,
};
