// PREVIEW-ONLY SCAFFOLDING — mirrors config/launcher.mock.ts. A realistic
// launch member (zero subscriptions) would only ever show Tools-tab
// "in-plan" (Score/Scrub) + "coming-soon" (everything else), and both
// bundles would always read coming-soon (they cover inactive tools) — so
// this fixture forces REIpack active-but-unowned to exercise the
// "available" purchasable path (status pill + learn-more tiers), while
// leaving both bundles coming-soon exactly as real launch data would.
// Gated behind TOOLS_PREVIEW_MOCK_MEMBER in lib/storeCatalog.ts; never read
// by the real (Prisma) path.

import type { StoreData } from "@/types/store";

export const mockStoreData: StoreData = {
  member: {
    name: "Preview Member",
    walletBalance: 42,
    currentBundleSlug: null,
    role: "user",
  },
  tools: [
    {
      id: "preview-score",
      slug: "score",
      brandSlug: "rei-score",
      name: "REIscore",
      tagline: "Placeholder tagline: instant deal scoring.",
      hook: "Placeholder hook: know if it's a deal in seconds.",
      compareCopy: ["Placeholder: ARV + comps", "Placeholder: offer ranges", "Placeholder: MAO calc"],
      unit: "analyses",
      active: true,
      featureSlug: "score",
      creditCost: 5,
      unitsPerDebit: 1,
      meteringShape: "per_cycle",
      status: "in-plan",
      tiers: [
        { id: "score-base", level: "base", name: "REIscore", priceCents: 0, allowance: 10, stripePriceId: null },
        { id: "score-plus", level: "plus", name: "REIscore+", priceCents: 2500, allowance: 50, stripePriceId: null },
        { id: "score-pro", level: "pro", name: "REIscore Pro", priceCents: 6900, allowance: 175, stripePriceId: null },
      ],
      hasHigherTier: true,
    },
    {
      id: "preview-scrub",
      slug: "scrub",
      brandSlug: "rei-scrub",
      name: "REIscrub",
      tagline: "Placeholder tagline: clean lead lists.",
      hook: "Placeholder hook: dedupe and scrub before you dial.",
      compareCopy: ["Placeholder: DNC scrub", "Placeholder: dedupe"],
      unit: "lookups",
      active: true,
      featureSlug: "scrub",
      creditCost: 0,
      unitsPerDebit: 1,
      meteringShape: "none",
      status: "in-plan",
      tiers: [{ id: "scrub-base", level: "base", name: "REIscrub", priceCents: 0, allowance: null, stripePriceId: null }],
      hasHigherTier: false,
    },
    {
      // Forced active-but-unowned so the "available" (purchasable) pill and
      // learn-more tiers render — real launch has pack.active = false.
      id: "preview-pack",
      slug: "pack",
      brandSlug: "rei-pack",
      name: "REIpack",
      tagline: "Placeholder tagline: buyer list packaging.",
      hook: "Placeholder hook: package deals for your buyer list fast.",
      compareCopy: ["Placeholder: flyer generation", "Placeholder: buyer matching"],
      unit: "packets",
      active: true,
      featureSlug: "pack",
      creditCost: 1,
      unitsPerDebit: 1,
      meteringShape: "per_cycle",
      status: "available",
      tiers: [{ id: "pack-base", level: "base", name: "REIpack", priceCents: 1900, allowance: 150, stripePriceId: null }],
      hasHigherTier: false,
    },
    {
      id: "preview-ask",
      slug: "ask",
      brandSlug: "rei-ask",
      name: "REIask",
      tagline: "Placeholder tagline: AI deal Q&A.",
      hook: "Placeholder hook: ask anything about your pipeline.",
      compareCopy: ["Placeholder: natural-language queries", "Placeholder: deal summaries"],
      unit: "queries",
      active: false,
      featureSlug: "ask",
      creditCost: 1,
      unitsPerDebit: 5,
      meteringShape: "per_cycle",
      status: "coming-soon",
      tiers: [],
      hasHigherTier: false,
    },
    {
      id: "preview-acq",
      slug: "acq",
      brandSlug: "rei-acq",
      name: "REIacq",
      tagline: "Placeholder tagline: acquisitions pipeline.",
      hook: "Placeholder hook: manage acquisitions end-to-end.",
      compareCopy: ["Placeholder: pipeline stages", "Placeholder: offer tracking"],
      unit: "handoffs",
      active: false,
      featureSlug: "bots",
      creditCost: 10,
      unitsPerDebit: 1,
      meteringShape: "by_volume",
      status: "coming-soon",
      tiers: [],
      hasHigherTier: false,
    },
    {
      id: "preview-dispo",
      slug: "dispo",
      brandSlug: "rei-dispo",
      name: "REIdispo",
      tagline: "Placeholder tagline: dispo automation.",
      hook: "Placeholder hook: move contracts faster.",
      compareCopy: ["Placeholder: buyer blasts", "Placeholder: contract tracking"],
      unit: "handoffs",
      active: false,
      featureSlug: "bots",
      creditCost: 10,
      unitsPerDebit: 1,
      meteringShape: "by_volume",
      status: "coming-soon",
      tiers: [],
      hasHigherTier: false,
    },
  ],
  packs: [
    { id: "preview-pack-100", slug: "pack-100", credits: 100, priceCents: 1800, stripePriceId: null },
    { id: "preview-pack-250", slug: "pack-250", credits: 250, priceCents: 4000, stripePriceId: null },
    { id: "preview-pack-600", slug: "pack-600", credits: 600, priceCents: 9000, stripePriceId: null, bestValue: true },
  ],
  bundles: [
    {
      // Coming-soon: covers ask, inactive in this fixture (matches real
      // launch data — no forcing needed to demonstrate this state).
      id: "preview-bundle-plus",
      slug: "bundle-plus",
      name: "REItools+",
      level: "plus",
      priceCents: 4600,
      lines: [
        { featureSlug: "score", level: "plus", tierId: "preview-tier-score-plus", priceCents: 2900, stripePriceId: null },
        { featureSlug: "ask", level: "base", tierId: "preview-tier-ask-base", priceCents: 2900, stripePriceId: null },
      ],
      tagline: "Placeholder tagline: for active dispo.",
      available: false,
      coverageLines: ["REIscore — 50 analyses/mo", "REIask — 500 queries/mo"],
      coversFeatureSlugs: ["score", "ask"],
    },
    {
      id: "preview-bundle-pro",
      slug: "bundle-pro",
      name: "REItools Pro",
      level: "pro",
      priceCents: 17300,
      lines: [
        { featureSlug: "score", level: "pro", tierId: "preview-tier-score-pro", priceCents: 4900, stripePriceId: null },
        { featureSlug: "ask", level: "plus", tierId: "preview-tier-ask-plus", priceCents: 4900, stripePriceId: null },
        { featureSlug: "bots", level: "base", tierId: "preview-tier-bots-base", priceCents: 9900, stripePriceId: null },
      ],
      tagline: "Placeholder tagline: full pipeline coverage.",
      bestValue: true,
      available: false,
      coverageLines: [
        "REIscore — 175 analyses/mo",
        "REIask — 1,500 queries/mo",
        "REIclose — 60 handoffs/mo",
      ],
      coversFeatureSlugs: ["score", "ask", "bots"],
    },
  ],
  coreBaseline: {
    name: "Core",
    tagline: "Placeholder tagline: your baseline REIblast membership access.",
    coverageLines: ["REIscore — 10 analyses/mo included", "REIscrub — Unlimited lookups/mo included"],
  },
  addons: [
    {
      id: "op-direct-site",
      slug: "site",
      name: "REI/site",
      tagline: "Placeholder tagline: a compliant site built to book you deals.",
      hook: "Placeholder hook: a conversion-built website wired straight into your CRM, done for you start to finish.",
      compareCopy: ["Placeholder: full build + SEO", "Placeholder: routes leads into your CRM"],
      priceCents: 50000,
      toolSlug: "rei-site",
    },
    {
      id: "op-direct-kit",
      slug: "kit",
      name: "REI/kit",
      tagline: "Placeholder tagline: look legit — logo and brand kit, done for you.",
      hook: "Placeholder hook: a full logo and brand kit so you look established from day one.",
      compareCopy: ["Placeholder: logo + brand marks", "Placeholder: ready for site, packets, signage"],
      priceCents: 25000,
      toolSlug: "rei-kit",
    },
  ],
  membership: { name: "REIblast", priceCents: 5700 },
};
